# Other keys not listed here may be retrieved during a playbook run from the apps config file

homepage_nzbget_username: 
homepage_nzbget_password:  

# Authentik
homepage_authentik_key: 

# Portainer
homepage_portainer_key:
homepage_portainer_env_id: 1 # default: 1 - Change this to match your Portainer environment ID 

# Jellyfin
homepage_jellyfin_key: 

# Emby
homepage_emby_key: 

# Autobrr
homepage_autobrr_key: 
